# Generated by Django 5.1 on 2024-08-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='score',
        ),
        migrations.AddField(
            model_name='candidate',
            name='cover_letter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(upload_to='resumes/'),
        ),
    ]
